ALTER TABLE `User`
  ADD COLUMN `username` VARCHAR(191) NULL,
  ADD COLUMN `cpf` VARCHAR(191) NULL,
  ADD COLUMN `cnh` VARCHAR(191) NULL,
  ADD COLUMN `legacyStatus` VARCHAR(191) NOT NULL DEFAULT 'Novo',
  ADD COLUMN `company` VARCHAR(191) NULL,
  ADD COLUMN `jobTitle` VARCHAR(191) NULL,
  ADD COLUMN `phone` VARCHAR(191) NULL,
  ADD COLUMN `address` TEXT NULL,
  ADD COLUMN `zipCode` VARCHAR(191) NULL,
  ADD COLUMN `city` VARCHAR(191) NULL,
  ADD COLUMN `state` VARCHAR(191) NULL,
  ADD COLUMN `secondaryAddress` VARCHAR(191) NULL,
  ADD COLUMN `secondaryNumber` VARCHAR(191) NULL,
  ADD COLUMN `secondaryComplement` VARCHAR(191) NULL,
  ADD COLUMN `neighborhood` VARCHAR(191) NULL,
  ADD COLUMN `notes` TEXT NULL,
  ADD COLUMN `facebook` VARCHAR(191) NULL,
  ADD COLUMN `instagram` VARCHAR(191) NULL,
  ADD COLUMN `youtube` VARCHAR(191) NULL,
  ADD COLUMN `forcePasswordChange` BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX `User_username_key` ON `User`(`username`);
CREATE UNIQUE INDEX `User_cpf_key` ON `User`(`cpf`);

ALTER TABLE `Role`
  ADD COLUMN `parentRoleId` VARCHAR(191) NULL,
  ADD COLUMN `functionName` VARCHAR(191) NULL,
  ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'Ativo';

ALTER TABLE `Role`
  ADD CONSTRAINT `Role_parentRoleId_fkey`
  FOREIGN KEY (`parentRoleId`) REFERENCES `Role`(`id`)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `Section`
  ADD COLUMN `visits` INTEGER NOT NULL DEFAULT 0;
